import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/header/Header";
import { ToastProvider } from "@/providers/ToastProvider";
import { integralCF, satoshi } from "@/font/Font";

export const metadata: Metadata = {
  title: "Shop App",
  description: "Generated by shop magazine",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${integralCF.className} ${satoshi.className}`}
    >
      <body className="antialiased">
        <ToastProvider />
        <Header />
        {children}
      </body>
    </html>
  );
}
